[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/admin-api"
  to = "/.netlify/functions/admin-api"
  status = 200
